/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CertificadoCodigoRouteImport } from './routes/certificado.$codigo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificadoCodigoRoute = CertificadoCodigoRouteImport.update({
  id: '/certificado/$codigo',
  path: '/certificado/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certificado/$codigo': typeof CertificadoCodigoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certificado/$codigo': typeof CertificadoCodigoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/certificado/$codigo': typeof CertificadoCodigoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/certificado/$codigo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/certificado/$codigo'
  id: '__root__' | '/' | '/certificado/$codigo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CertificadoCodigoRoute: typeof CertificadoCodigoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificado/$codigo': {
      id: '/certificado/$codigo'
      path: '/certificado/$codigo'
      fullPath: '/certificado/$codigo'
      preLoaderRoute: typeof CertificadoCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CertificadoCodigoRoute: CertificadoCodigoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
