/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerificarCodeRouteImport } from './routes/verificar.$code'
import { Route as CertificadoCodigoRouteImport } from './routes/certificado.$codigo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificarCodeRoute = VerificarCodeRouteImport.update({
  id: '/verificar/$code',
  path: '/verificar/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificadoCodigoRoute = CertificadoCodigoRouteImport.update({
  id: '/certificado/$codigo',
  path: '/certificado/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certificado/$codigo': typeof CertificadoCodigoRoute
  '/verificar/$code': typeof VerificarCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certificado/$codigo': typeof CertificadoCodigoRoute
  '/verificar/$code': typeof VerificarCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/certificado/$codigo': typeof CertificadoCodigoRoute
  '/verificar/$code': typeof VerificarCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/certificado/$codigo' | '/verificar/$code'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/certificado/$codigo' | '/verificar/$code'
  id: '__root__' | '/' | '/certificado/$codigo' | '/verificar/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CertificadoCodigoRoute: typeof CertificadoCodigoRoute
  VerificarCodeRoute: typeof VerificarCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verificar/$code': {
      id: '/verificar/$code'
      path: '/verificar/$code'
      fullPath: '/verificar/$code'
      preLoaderRoute: typeof VerificarCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificado/$codigo': {
      id: '/certificado/$codigo'
      path: '/certificado/$codigo'
      fullPath: '/certificado/$codigo'
      preLoaderRoute: typeof CertificadoCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CertificadoCodigoRoute: CertificadoCodigoRoute,
  VerificarCodeRoute: VerificarCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
